stages:
  - build
  
build-apk:
    stage: build
    script:
       - /Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -projectPath $CI_PROJECT_DIR -buildTarget Android -logFile buildAndroid.log
       - ls 
    artifacts:
      when: always
      expire_in: 10 days
      paths:
        - buildAndroid.log