stages:
  - build-android
  - android-tests
  - build-ios
  - ios-tests
  - appium-tests
  - deploy
  
build-apk:
    stage: build-android
    tags:
      - unity
    script:
    - /Applications/Unity/Unity.app/Contents/MacOS/Unity -projectPath $CI_PROJECT_DIR -executeMethod AltUnityTesterEditor.InitEditorConfiguration -logFile initEditorConfiguration.log -quit
    - /Applications/Unity/Unity.app/Contents/MacOS/Unity -projectPath $CI_PROJECT_DIR -executeMethod AltUnityTesterEditor.AndroidBuildFromCommandLine -logFile buildAndroid.log -quit
       - ls 
    artifacts:
      when: always
      expire_in: 10 days
      paths:
        - buildAndroid.log
        - sampleGame.apk

run-csharp-android-tests:
    stage: android-tests
    tags:
        - unity
    script:
        - adb uninstall fi.altom.altunitytester || true
        - adb install sampleGame.apk
        - adb shell am start -n fi.altom.altunitytester/com.unity3d.player.UnityPlayerActivity
        - /Applications/Unity/Unity.app/Contents/MacOS/Unity -projectPath $CI_PROJECT_DIR -executeMethod AltUnityTesterEditor.RunAllTestsAndroid -logFile csharpAndroidTests.log -quit 


run-python-android-tests:
    stage: android-tests
    tags:
        - unity
    script:
        - adb uninstall fi.altom.altunitytester || true
        - adb install sampleGame.apk
        - adb shell am start -n fi.altom.altunitytester/com.unity3d.player.UnityPlayerActivity
        - adb forward --remove-all
        - adb forward tcp:13000 tcp:13000
        - virtualenv altunitytests
        - source altunitytests/bin/activate
        - pip install Appium-Python-Client
        - pip uninstall --yes altunityrunner || true
        - pip install -e Assets/AltUnityTester/Bindings/python
        - sleep 30
        - python Assets/AltUnityTester/Bindings/python_bindings_tests.py


run-java-android-tests:
    stage: android-tests
    tags:
        - unity
    script:
        - adb uninstall fi.altom.altunitytester || true
        - adb install sampleGame.apk
        - adb shell am start -n fi.altom.altunitytester/com.unity3d.player.UnityPlayerActivity
        - adb forward --remove-all
        - adb forward tcp:13000 tcp:13000
        - cd Assets/AltUnityTester/Bindings/java
        - mvn test

build-ipa:
    stage: build-ios
    tags:
      - unity
    script:
    - /Applications/Unity/Unity.app/Contents/MacOS/Unity -projectPath $CI_PROJECT_DIR -executeMethod AltUnityTesterEditor.InitEditorConfiguration -logFile initEditorConfiguration.log -quit
    - /Applications/Unity/Unity.app/Contents/MacOS/Unity -projectPath $CI_PROJECT_DIR -executeMethod AltUnityTesterEditor.IosBuildFromCommandLine -logFile buildIos.log
    - sleep 60
    - ls 
    artifacts:
      when: always
      expire_in: 10 days
      paths:
        - buildIos.log

run-csharp-android-tests:
    stage: ios-tests
    tags:
        - unity
    script:
        - /Applications/Unity/Unity.app/Contents/MacOS/Unity -projectPath $CI_PROJECT_DIR -executeMethod AltUnityTesterEditor.RunAllTestsIos -logFile csharpIosTests.log -quit        
        
# # run-appium-tests:
#     stage: appium-tests
#     tags:
#         - unity
#     script:
#         - virtualenv altunitytests
#         - source altunitytests/bin/activate
#         - killall node || true
#         - appium >> appium.log & 
#         - pip install Appium-Python-Client
#         - pip uninstall --yes altunityrunner || true
#         - pip install -e Assets/AltUnityTester/Bindings/python
#         - sleep 30
#         - python Assets/ExamplesAndTests\ \(can\ be\ deleted\)/sampletest.py
#         - killall node || true
#     artifacts:
#         when: always
#         expire_in: 10 days
#         paths:
#             - appium.log

deploy-altunitytester-python:
    stage: deploy
    when: manual
    only:
        refs:
            - master
    tags:
        - unity
    script:
        - cd Assets/AltUnityTester/Bindings/python
        - python setup.py sdist upload -r pypi