stages:
  - build
  
build-apk:
    stage: build
    tags:
      - unity
    script:
       - /Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -projectPath $CI_PROJECT_DIR -executeMethod PerformBuild.AndroidDefault -logFile buildAndroid.log
       - ls 
    artifacts:
      when: always
      expire_in: 10 days
      paths:
        - buildAndroid.log
        - sampleGame.apk